name: build
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  publish:
    runs-on: windows-latest
    strategy:
      matrix:
        sys:
          - mingw64
    steps:
      - uses: actions/checkout@v2

      - name: Set up mysys2
        uses: msys2/setup-msys2@v2
      - name: Install curl
        shell: msys2 {0}
        run: |
          pacman -S mingw-w64-x86_64-curl --noconfirm 

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: build
        run: ./gradlew.bat build
